version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env

  frontend:
    build: ./frontend-admin
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: