version: '3.8'
services:
  db:
    image: postgres:15
    ports:
      - "5432:5432" 
    restart: always
    environment:
      # These variables tell Postgres what password to set on startup
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vinayak
      - POSTGRES_DB=resty
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env

  frontend:
    build: ./frontend-admin
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: