"""add restaurant_id to orders

Revision ID: d1d3c7f24506
Revises: 
Create Date: 2026-03-31 00:32:43.911576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d3c7f24506'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'menu_categories', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_constraint(op.f('fk_menu_items_subcategory'), 'menu_items', type_='foreignkey')
    op.create_foreign_key(None, 'menu_items', 'menu_subcategories', ['subcategory_id'], ['id'])
    op.drop_column('menu_items', 'category')
    op.create_foreign_key(None, 'menu_subcategories', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('orders', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'restaurants', ['restaurant_id'], ['id'])
    op.create_foreign_key(None, 'restaurant_users', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant_users', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'restaurant_id')
    op.drop_constraint(None, 'menu_subcategories', type_='foreignkey')
    op.add_column('menu_items', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_menu_items_subcategory'), 'menu_items', 'menu_categories', ['subcategory_id'], ['id'])
    op.drop_constraint(None, 'menu_categories', type_='foreignkey')
    # ### end Alembic commands ###
