name: Deploy to EC2

on:
  push:
    branches: [ main ] # Triggered when you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            # 1. Move to home directory
            cd /home/ubuntu
            
            # 2. If the folder doesn't exist, clone the repo
            if [ ! -d "Resty" ]; then
              git clone https://github.com/VinayakChavda/Resty.git
            fi
            
            # 3. Enter the folder
            cd Resty
            
            # 4. Pull the latest code from GitHub
            git pull origin main
            
            # 5. Run Docker (make sure your .env is already in this folder!)
            sudo docker-compose down
            sudo docker-compose up --build -d